//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Course
    {
        public int CourseID { get; set; }

        [Display(Name = "Course Name"), Required, MaxLength(100)]
        public string CourseName { get; set; }

        [Display(Name = "Course Duration in months"), Required]
        public int CourseDuration { get; set; }
        [Display(Name = "Degree"), Required]

        public int DegreeID { get; set; }

        public virtual Degree Degree { get; set; }
    }
}
