//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentTask.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int StudentID { get; set; }

        [Required, MaxLength(100)]
        public string Forenames { get; set; }

        [Required, MaxLength(100)]
        public string Surname { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date of Birth"), Required, DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }

        [Display(Name = "First Name"), Required, MaxLength(100)]
        public string FirstName { get; set; }

        [Display(Name = "Full Name"), Required, MaxLength(100)]
        public string FullName { get; set; }

        [Display(Name = "Degree"), Required]
        public int DegreeID { get; set; }

        [Display(Name = "Email"), Required, MaxLength(100), DataType(DataType.EmailAddress)]
        public string EmailAddress { get; set; }

        public virtual Degree Degree { get; set; }
    }
}

